
version: 2.1

executors:
  cypress_executor:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/cypress
    
commands:
  cypress_autotest:
    description: "Cypress auto test"
    parameters:
      ENV:
        type: string
      BROWSER:
        type: string
        default: ""
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/cypress-autotest.tar
      - run:
          name: run test case
          environment:
            ENV: << parameters.ENV >>
            BROWSER: << parameters.BROWSER >>
          command: |
            docker run -e ENV=${ENV} -e BROWSER=${BROWSER} cypress-autotest
            
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
       
  cy_ui_dev:
    executor: cypress_executor
    parameters:
      IS_SEND_NOTIFICATION:
        type: boolean
        default: false
    steps:
      - cypress_autotest:
          ENV: "dev"
          BROWSER: "chrome"

workflows:
  version: 2
  app-ui-test:
    jobs:
      - build
      - cy_ui_dev:
          requires:
            - build
