version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Trigger the Build Job
          command: |
            echo "hello world" # run the `echo` command
            printf "Triggering an $PROJECT build on the $CIRCLE_BRANCH branch\n\n"

            curl -u f29269792a9786ef612ece08e58d13886677ded3: \
              -d build_parameters[CIRCLE_JOB]=cypress-pipeline \
              https://circleci.com/api/v1/project/NextDeveloperTeam/CypressAutoTest/tree/master

            printf "\n\nBuild triggered\n\n"
            printf "Follow the progress of the build on \nhttps://circleci.com/gh/NextDeveloperTeam/CypressAutoTest/tree/master"
